i2c:
  sda: GPIO38
  scl: GPIO39

font:
  - file: "gfonts://Open Sans"
    id: font_small
    size: 12

  - file: "gfonts://Open Sans"
    id: font_big
    size: 20

globals:
  - id: oled_page
    type: int
    initial_value: '0'

interval:
  - interval: 7s
    then:
      - lambda: |-
          id(oled_page) = (id(oled_page) + 1) % 2;

sensor:
  - platform: ecodan
    ecodan_id: ecodan_instance

    hot_water_temperature:
      id: hot_water_temp

    hot_water_temperature_thw5a:
      id: hot_water_temp_thw5a

    compressor_frequency:
      id: compressor_freq

    flow_rate:
      id: flow_rate

    boiler_flow_temp:
      id: flow_temp

    boiler_return_temp:
      id: return_temp

    z1_flow_temp_target:
      id: setpoint

    outside_temp:
      id: outdoor_temp

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 7s

    lambda: |-
      if (id(oled_page) == 0) {

        it.printf(0, 0, id(font_small),
          "^%.1f v%.1f %.0fHz",
          id(hot_water_temp).state,
          id(hot_water_temp_thw5a).state,
          id(compressor_freq).state
        );

        it.printf(0, 14, id(font_small),
          "Flow %.0f  T %.0f",
          id(flow_rate).state,
          id(flow_temp).state
        );

        it.printf(0, 28, id(font_small),
          "Ret %.0f  SP %.0f",
          id(return_temp).state,
          id(setpoint).state
        );

      } else {

        it.printf(0, 0, id(font_big), "Valjas:");

        it.printf(0, 32, id(font_big),
          "%.0f C",
          id(outdoor_temp).state
        );
      }
